# Generated by Django 4.2 on 2023-04-20 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField(max_length=20)),
                ('customer_password', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_first_name', models.CharField(max_length=40)),
                ('customer_last_name', models.CharField(max_length=40)),
                ('customer_street', models.CharField(max_length=50)),
                ('customer_city', models.CharField(max_length=50)),
                ('customer_zipcode', models.CharField(max_length=50)),
                ('customer_phone_number', models.CharField(max_length=10)),
                ('customer_credit_card_number', models.CharField(max_length=16)),
                ('customer_card_expiry', models.CharField(max_length=6)),
                ('customer_credit_card_cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_subtotal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('invoice_tax', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_clothing_type', models.CharField(max_length=20)),
                ('order_clothing_quantity', models.IntegerField()),
                ('order_delivery_street', models.CharField(max_length=40)),
                ('order_delivery_city', models.CharField(max_length=40)),
                ('order_delivery_state', models.CharField(max_length=40)),
                ('order_delivery_zipcode', models.CharField(max_length=15)),
                ('order_delivery_contact_number', models.CharField(max_length=10)),
                ('order_pick_up_required', models.BooleanField(verbose_name=False)),
                ('order_date_created', models.DateTimeField(auto_now_add=True)),
                ('order_estimated_completion_date', models.DateField(blank=True, null=True)),
                ('order_sub_total', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('service_price_per_unit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('service_est_time_per_unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_clothing_type', models.CharField(max_length=20)),
                ('service_price_per_unit', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=20)),
                ('house_no', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
